(() => {
  const $ = id => document.getElementById(id);
  const CFG = window.THREATWATCH_CONFIG || {};
  const SESSION_MINUTES = Number(CFG.sessionMinutes || 60);
  const SESSION_KEY = 'threatwatch-v12-session';
  const LOG_KEY = 'threatwatch-v12-log';
  let peer=null, conn=null, mediaCall=null; const activeConnections=new Map(); const mediaCalls=new Map();
  let sessionId=null, pairingToken=null, participantId=null, deadline=0, ended=false;
  let expiryTimer=null, reconnectTimer=null, pingTimer=null, watchdogTimer=null, pingAt=0, lastPongAt=0, reconnectAttempts=0;
  let photoItems=[], photoCount=0, viewerIndex=-1, viewerScale=1, latestMapUrl='';
  const pendingPhotos=new Map();

  const CONSOLE_DB='threatwatch-device-a-v12'; let consoleDb=null;
  function openDb(){return new Promise(resolve=>{if(!('indexedDB' in window)){resolve(null);return}const req=indexedDB.open(CONSOLE_DB,2);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'id',autoIncrement:true});if(!db.objectStoreNames.contains('locations'))db.createObjectStore('locations',{keyPath:'id',autoIncrement:true})};req.onsuccess=()=>{consoleDb=req.result;resolve(consoleDb)};req.onerror=()=>resolve(null)})}
  function dbAdd(store,value){return new Promise(resolve=>{if(!consoleDb){resolve(null);return}try{const tx=consoleDb.transaction(store,'readwrite');const req=tx.objectStore(store).add(value);req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null)}catch{resolve(null)}})}
  function dbDelete(store,id){return new Promise(resolve=>{if(!consoleDb){resolve();return}try{const tx=consoleDb.transaction(store,'readwrite');tx.objectStore(store).delete(Number(id));tx.oncomplete=()=>resolve();tx.onerror=()=>resolve()}catch{resolve()}})}
  function dbClear(store){return new Promise(resolve=>{if(!consoleDb){resolve();return}try{const tx=consoleDb.transaction(store,'readwrite');tx.objectStore(store).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>resolve()}catch{resolve()}})}
  function dbRead(store){return new Promise(resolve=>{if(!consoleDb){resolve([]);return}try{const req=consoleDb.transaction(store,'readonly').objectStore(store).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>resolve([])}catch{resolve([])}})}

  openDb().then(async()=>{for(const p of await dbRead('photos')) addPhoto(p.data,p.location,false,p.id,p.savedAt,p.filter,p.sticker);const locations=await dbRead('locations');const last=locations.at(-1);if(last)updateConsoleLocation(last,false);updateStorageSummary()});

  function saveSession(s){try{localStorage.setItem(SESSION_KEY,JSON.stringify(s))}catch{}}
  function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
  function saveLogLine(line){try{const arr=JSON.parse(localStorage.getItem(LOG_KEY)||'[]');arr.push(line);while(arr.length>400)arr.shift();localStorage.setItem(LOG_KEY,JSON.stringify(arr))}catch{}}
  function loadLogs(){try{return JSON.parse(localStorage.getItem(LOG_KEY)||'[]')}catch{return []}}
  function clearStoredLog(){try{localStorage.removeItem(LOG_KEY)}catch{}}
  const log=msg=>{const line=`[${new Date().toLocaleTimeString()}] ${msg}`;const el=$('log');if(el){el.textContent+=line+'\n';el.scrollTop=el.scrollHeight}saveLogLine(line)};
  loadLogs().forEach(x=>$('log').textContent+=x+'\n');
  const toast=msg=>{const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)};
  window.addEventListener('error',e=>log(`JavaScript error: ${e.message||'unknown'}`)); window.addEventListener('unhandledrejection',e=>log(`Unhandled error: ${e.reason?.message||String(e.reason)}`));

  const basePath=()=>location.pathname.endsWith('/')?location.pathname:location.pathname.slice(0,location.pathname.lastIndexOf('/')+1);
  const randomToken=()=>{const a=new Uint8Array(24);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')};
  const participantUrl=()=>location.origin+basePath()+'participant.html?session='+encodeURIComponent(sessionId)+'&token='+encodeURIComponent(pairingToken);
  const setBadge=(text,state='neutral')=>{const e=$('onlineBadge');e.textContent=text;e.className=`statusBadge ${state}`};
  const setPill=(id,text,on)=>{const e=$(id);e.textContent=text;e.className=`tinyStatus ${on?'on':'off'}`};
  const check=(id,on)=>$(id).classList.toggle('ok',!!on);
  function browserInfo(ua){let browser='Unknown';if(/Edg\//.test(ua))browser='Edge';else if(/Chrome\//.test(ua))browser='Chrome';else if(/Firefox\//.test(ua))browser='Firefox';else if(/Safari\//.test(ua)&&!/Chrome\//.test(ua))browser='Safari';const platform=/Android/i.test(ua)?'Android':/iPhone|iPad|iPod/i.test(ua)?'iOS':/Windows/i.test(ua)?'Windows':/Mac/i.test(ua)?'macOS':'Other';return{browser,platform}}

  function renderQR(url){const box=$('qrcode');box.innerHTML='';try{if(typeof QRCode!=='undefined'){new QRCode(box,{text:url,width:276,height:276,correctLevel:QRCode.CorrectLevel.H});$('qrState').textContent='READY';return}}catch(e){log('QR renderer failed: '+e.message)}const img=document.createElement('img');img.alt='THREATWATCH pairing QR';img.width=276;img.height=276;img.referrerPolicy='no-referrer';img.src='https://api.qrserver.com/v1/create-qr-code/?size=276x276&margin=8&data='+encodeURIComponent(url);img.onload=()=>{$('qrState').textContent='READY'};img.onerror=()=>{box.innerHTML='<div class="qrLoading"><b>QR unavailable</b><small>Use the participant link.</small></div>';$('qrState').textContent='LINK READY';log('QR fallback unavailable.')};box.appendChild(img)}

  function resetUI(){
    renderDeviceList();
    $('deviceStatus').textContent='WAITING';$('deviceSub').textContent='No participant connected';$('participantPeer').textContent='No device';$('pairedAt').textContent='Not paired';$('participantPlatform').textContent='—';$('participantBrowser').textContent='—';$('connectionQuality').textContent='—';$('latencyText').textContent='Waiting for participant';
    setPill('cameraPill','OFF',false);setPill('locationPill','OFF',false);setPill('participantState','WAITING',false);$('stopLocationBtn').disabled=true;$('remotePhotoPreview').hidden=true;$('remotePhotoPreview').src='';$('videoEmpty').style.display='grid';$('liveTag').hidden=true;const rv=$('remoteVideo');if(rv){rv.hidden=true;rv.srcObject=null}document.querySelector('.mediaFrame')?.classList.remove('live');$('cameraInfo').textContent='Waiting for participant capture';$('transferInfo').textContent='Ready';$('lat').textContent=$('lon').textContent=$('acc').textContent='—';$('map').textContent='Waiting for participant location';$('openMapBtn').disabled=true;latestMapUrl='';check('checkConnection',false);check('checkCamera',false);check('checkLocation',false);
  }
  function destroyPeer(){for(const c of activeConnections.values()){try{c.close()}catch{}}activeConnections.clear();try{peer?.destroy()}catch{}peer=null;conn=null;for(const call of mediaCalls.values()){try{call.close()}catch{}}mediaCalls.clear();try{mediaCall?.close()}catch{}mediaCall=null}

  function startExpiry(){clearInterval(expiryTimer);const tick=()=>{const left=Math.max(0,deadline-Date.now());const sec=Math.ceil(left/1000);const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),ss=sec%60;$('expiryText').textContent=h?`${h}:${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`:`${m}:${String(ss).padStart(2,'0')}`;if(!left)endSession('Session expired.')};tick();expiryTimer=setInterval(tick,500)}
  const devicePings=new Map();
  function startPing(){clearInterval(pingTimer);clearInterval(watchdogTimer);lastPongAt=Date.now();const every=Number(CFG.pingIntervalMs||12000);pingTimer=setInterval(()=>{for(const c of activeConnections.values()){if(c.open){const t=Date.now();devicePings.set(c.peer,t);try{c.send({type:'ping',t})}catch{}}}},every);watchdogTimer=setInterval(()=>{if(ended)return;const stale=Number(CFG.staleConnectionMs||45000);for(const c of activeConnections.values()){const last=devicePings.get(c.peer)||Date.now();if(c.open&&Date.now()-last>stale){try{c.close()}catch{}log(`Connection watchdog closed stale device: ${c.__twMeta?.deviceId||c.peer}`)}}},5000)}

  function sendConfig(){return {host:CFG.peer?.host,port:CFG.peer?.port,path:CFG.peer?.path,secure:CFG.peer?.secure,key:CFG.peer?.key,config:{iceServers:CFG.iceServers||[{urls:'stun:stun.l.google.com:19302'}],sdpSemantics:'unified-plan',iceTransportPolicy:'all',iceCandidatePoolSize:8},debug:0}}

  async function processIncomingBinary(buf, sourceConn){
    const p=pendingPhotos.get(sourceConn?.peer);if(!p)return;
    p.parts.push(buf);p.received++;$('transferInfo').textContent=`Receiving photo ${Math.round(p.received/p.total*100)}%`;
    if(p.received>=p.total){pendingPhotos.delete(p.id);const blob=new Blob(p.parts,{type:p.mime||'image/jpeg'});const data=await blobToDataURL(blob);const id=await dbAdd('photos',{data,location:p.location||null,filter:p.filter||null,sticker:p.sticker||null,savedAt:p.savedAt||Date.now()});addPhoto(data,p.location,true,id,p.savedAt,p.filter,p.sticker);$('transferInfo').textContent='Ready';$('cameraInfo').textContent='Latest capture received';setPill('cameraPill','ON',true);check('checkCamera',true);log(`Photo received: ${p.filter?'Filter':'Selfie'}${p.location?' + location':''}.`);toast('New photo received')}
  }
  function blobToDataURL(blob){return new Promise(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>resolve('');fr.readAsDataURL(blob)})}

  function renderDeviceList(){
    const wrap=$('deviceList'); if(!wrap)return; const items=[...activeConnections.values()].filter(c=>c.open);
    $('deviceCount').textContent=`${items.length} device${items.length===1?'':'s'}`;
    if(!items.length){wrap.innerHTML='<div class="deviceEmpty">No participant devices connected.</div>';return;}
    wrap.innerHTML='';
    for(const c of items){const m=c.__twMeta||{};const item=document.createElement('article');item.className='deviceItem';item.dataset.peer=c.peer;item.innerHTML=`<div class="deviceItemTop"><strong>${m.deviceId||c.peer}</strong><span class="tinyStatus on">CONNECTED</span></div><div class="deviceItemMeta"><div><span>Platform</span><strong>${m.platform||'—'}</strong></div><div><span>Browser</span><strong>${m.browser||'—'}</strong></div></div><small style="color:#8b94a4">Connected ${m.connectedAt||'—'}</small>`;wrap.appendChild(item)}
  }

  function wireConnection(c){
    c.on('open',()=>{reconnectAttempts=0;$('deviceStatus').textContent='CONNECTED';$('deviceSub').textContent=`${activeConnections.size||1} participant device${(activeConnections.size||1)===1?'':'s'}`;renderDeviceList();setPill('participantState','CONNECTED',true);check('checkConnection',true);setBadge('CONNECTED','good');$('sessionState').textContent='Participant connected';$('sessionMetric').textContent='ACTIVE';$('sessionSub').textContent=`${Math.round(SESSION_MINUTES/60)}-hour session`;startPing();log('Participant data channel opened.');});
    c.on('data',async data=>{
      if(data instanceof ArrayBuffer){await processIncomingBinary(data,c);return}if(typeof Blob!=='undefined'&&data instanceof Blob){await processIncomingBinary(await data.arrayBuffer(),c);return}if(data instanceof Uint8Array){await processIncomingBinary(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),c);return}
      if(!data||typeof data!=='object')return;
      if(data.type==='hello'){if(data.token!==pairingToken){log('Rejected participant with invalid pairing token.');try{c.send({type:'command',command:'session-ended'});c.close()}catch{}return}const info=browserInfo(data.ua||'');c.__twMeta={deviceId:data.deviceId||c.peer,platform:info.platform,browser:info.browser,connectedAt:new Date().toLocaleTimeString()};participantId=c.peer;activeConnections.set(c.peer,c);$('participantPeer').textContent=`${activeConnections.size} device${activeConnections.size===1?'':'s'}`;$('pairedAt').textContent=c.__twMeta.connectedAt;$('participantPlatform').textContent=info.platform;$('participantBrowser').textContent=info.browser;renderDeviceList();log(`Participant paired: ${c.__twMeta.deviceId}`);toast('Participant connected')}
      else if(data.type==='pong'){lastPongAt=Date.now();devicePings.delete(c.peer);const ms=Date.now()-Number(data.t||Date.now());$('connectionQuality').textContent=ms<120?'EXCELLENT':ms<300?'GOOD':ms<700?'FAIR':'WEAK';$('latencyText').textContent=`${ms} ms • ${activeConnections.size} device${activeConnections.size===1?'':'s'}`}
      else if(data.type==='heartbeat'){$('latencyText').textContent='Heartbeat '+new Date().toLocaleTimeString()}
      else if(data.type==='camera'){$('cameraInfo').textContent=data.enabled?'Camera ready on participant':'Camera closed';setPill('cameraPill',data.enabled?'ON':'OFF',!!data.enabled);check('checkCamera',!!data.enabled)}
      else if(data.type==='location'){updateConsoleLocation(data,true)}
      else if(data.type==='location-off'){setPill('locationPill','OFF',false);$('stopLocationBtn').disabled=true;check('checkLocation',false);log('Participant stopped location updates.')}
      else if(data.type==='photo-start'){pendingPhotos.set(c.peer,{...data,parts:[],received:0,total:Number(data.total||0)});$('transferInfo').textContent=`Receiving photo 0% from ${c.__twMeta?.deviceId||c.peer}`;setPill('cameraPill','ON',true)}
      else if(data.type==='photo-legacy'){const id=await dbAdd('photos',{data:data.data,location:data.location||null,filter:data.filter||null,sticker:data.sticker||null,savedAt:data.savedAt||Date.now()});addPhoto(data.data,data.location,true,id,data.savedAt,data.filter,data.sticker)}
      else if(data.type==='cancel-photo'){ $('transferInfo').textContent='Transfer cancelled'; pendingPhotos.delete(c.peer)}
    });
    c.on('close',()=>{activeConnections.delete(c.peer);pendingPhotos.delete(c.peer);const call=mediaCalls.get(c.peer);try{call?.close()}catch{}mediaCalls.delete(c.peer);if(mediaCall===call)mediaCall=[...mediaCalls.values()].at(-1)||null;if(conn===c){conn=[...activeConnections.values()].find(x=>x.open)||null}renderDeviceList();if(ended)return;if(activeConnections.size===0){clearInterval(pingTimer);$('deviceStatus').textContent='WAITING';$('deviceSub').textContent='No participant connected';setPill('participantState','DISCONNECTED',false);$('connectionQuality').textContent='—';$('latencyText').textContent='Waiting for participant';$('sessionState').textContent='Ready to pair again';setBadge('ONLINE','good');}else{$('deviceStatus').textContent='CONNECTED';$('deviceSub').textContent=`${activeConnections.size} participant devices`;};log(`Participant disconnected: ${c.__twMeta?.deviceId||c.peer}`)});
    c.on('error',e=>log('Data channel error: '+(e.message||'unknown')));
  }

  function connectPeer(){
    if(typeof Peer==='undefined'){$('sessionState').textContent='PeerJS unavailable';setBadge('ERROR','bad');log('PeerJS library unavailable.');return}
    try{peer=new Peer(sessionId,sendConfig())}catch(e){log('Peer startup error: '+e.message);retryPeer();return}
    peer.on('open',id=>{setBadge('ONLINE','good');$('sessionState').textContent='Ready to pair';if(!window.__twSignalingReadyLogged){log('Signaling ready: '+id);window.__twSignalingReadyLogged=true}});
    peer.on('connection',c=>{if(ended||!sessionId){c.close();return}activeConnections.set(c.peer,c);if(!conn||!conn.open)conn=c;participantId=c.peer;wireConnection(c);log('Participant connection accepted: '+c.peer)});
    peer.on('call',call=>{const deviceId=call.metadata?.deviceId||call.peer;mediaCalls.set(deviceId,call);mediaCall=call;call.answer();call.on('stream',stream=>{const v=$('remoteVideo');if(v){v.srcObject=stream;v.hidden=false;document.querySelector('.mediaFrame')?.classList.add('live');$('videoEmpty').style.display='none';$('liveTag').hidden=false;$('cameraInfo').textContent=`Live camera stream • ${deviceId}`;setPill('cameraPill','ON',true);check('checkCamera',true);log(`Live camera stream connected: ${deviceId}`)}});call.on('close',()=>{mediaCalls.delete(deviceId);if(mediaCall===call){mediaCall=[...mediaCalls.values()].at(-1)||null;const v=$('remoteVideo');if(mediaCall?.peerConnection){/* another device still streaming */}else if(v){v.srcObject=null;v.hidden=true;document.querySelector('.mediaFrame')?.classList.remove('live');$('liveTag').hidden=true;$('cameraInfo').textContent='Live camera stream ended';}}});log(`Incoming camera stream request: ${deviceId}`)});
    peer.on('disconnected',()=>{if(ended)return;setBadge('RECONNECTING');$('sessionState').textContent='Signaling disconnected; reconnecting…';try{peer.reconnect()}catch{retryPeer()}});
    peer.on('error',e=>{if(ended)return;setBadge('ERROR','bad');$('sessionState').textContent='Connection error: '+e.type;log('Peer error: '+e.type+(e.message?' — '+e.message:''));if(e.type==='unavailable-id')retryPeer()});
  }
  function retryPeer(){if(ended)return;clearTimeout(reconnectTimer);reconnectAttempts++;if(reconnectAttempts>Number(CFG.reconnectAttempts||20)){setBadge('OFFLINE','bad');$('sessionState').textContent='Network connection unavailable';log('Reconnect attempts exhausted. Check TURN configuration or network restrictions.');return}const base=Number(CFG.reconnectDelayMs||1500), max=Number(CFG.reconnectMaxDelayMs||15000);const delay=Math.min(max,base*Math.pow(1.45,Math.max(0,reconnectAttempts-1)));$('sessionState').textContent=`Reconnecting… attempt ${reconnectAttempts}`;reconnectTimer=setTimeout(()=>{try{peer?.destroy()}catch{}peer=null;connectPeer()},delay)}

  function startSession(forceNew=true){
    ended=false;clearTimeout(reconnectTimer);clearInterval(pingTimer);clearInterval(expiryTimer);destroyPeer();resetUI();
    if(forceNew||!sessionId){pairingToken=randomToken();sessionId=pairingToken.slice(0,20);deadline=Date.now()+SESSION_MINUTES*60000;saveSession({sessionId,pairingToken,deadline,active:true});}
    $('sessionId').textContent=sessionId;$('pairCode').textContent=pairingToken.slice(0,8).toUpperCase();$('joinUrl').textContent=participantUrl();$('copyBtn').disabled=false;$('shareBtn').disabled=false;$('regenerateBtn').disabled=false;$('endBtn').disabled=false;$('sessionMetric').textContent='READY';$('sessionSub').textContent=`${Math.round(SESSION_MINUTES/60)}-hour session`;$('sessionState').textContent='Starting secure connection…';$('expiryText').textContent='—';$('qrState').textContent='STARTING';renderQR(participantUrl());setBadge('STARTING');startExpiry();connectPeer();log(forceNew?'New session created.':'Session restored after refresh.');
  }
  function restoreOrStart(){const s=loadSession();if(s?.active&&s.sessionId&&s.pairingToken&&Number(s.deadline)>Date.now()){sessionId=s.sessionId;pairingToken=s.pairingToken;deadline=Number(s.deadline);startSession(false);return}startSession(true)}
  function endSession(reason='Session ended by console.'){
    if(ended)return;ended=true;clearInterval(expiryTimer);clearInterval(pingTimer);clearInterval(watchdogTimer);clearTimeout(reconnectTimer);try{conn?.send({type:'command',command:'session-ended'})}catch{}try{conn?.close()}catch{}try{mediaCall?.close()}catch{}destroyPeer();saveSession({sessionId,pairingToken,deadline,active:false});$('endBtn').disabled=true;$('shareBtn').disabled=true;$('copyBtn').disabled=true;$('regenerateBtn').disabled=true;$('sessionMetric').textContent='ENDED';$('sessionSub').textContent='Token invalidated';$('sessionState').textContent=reason;$('expiryText').textContent='ENDED';$('qrState').textContent='ENDED';setBadge('OFFLINE');log(reason)}
  function updateConsoleLocation(data,logIt=true){const lat=Number(data.lat),lon=Number(data.lon),accuracy=Number(data.accuracy);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;setPill('locationPill','ON',true);$('stopLocationBtn').disabled=false;$('lat').textContent=lat.toFixed(6);$('lon').textContent=lon.toFixed(6);$('acc').textContent=Number.isFinite(accuracy)?Math.round(accuracy)+' m':'—';const stamp=Number(data.timestamp||Date.now());$('locationInfo').textContent='Updated '+new Date(stamp).toLocaleTimeString();latestMapUrl=`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=17/${lat}/${lon}`;$('map').innerHTML=`<a target="_blank" rel="noopener" href="${latestMapUrl}">Open participant location ↗</a>`;$('openMapBtn').disabled=false;check('checkLocation',true);dbAdd('locations',{lat,lon,accuracy,timestamp:stamp,savedAt:Date.now()});if(logIt)log(`Location received: ${lat.toFixed(6)}, ${lon.toFixed(6)}.`)}

  function emptyGallery(){return '<div class="emptyGallery"><div>▧</div><b>No photos received</b><small>Participant captures will appear here.</small></div>'}
  function updateStorageSummary(){$('storageSummary')&&($('storageSummary').textContent=`${photoCount} photo${photoCount===1?'':'s'} stored locally`)}
  function refreshSelection(){const selected=photoItems.filter(x=>x.selected).length;$('deleteSelectedBtn').disabled=!selected;$('selectionInfo').textContent=selected?`${selected} selected`:'No selection'}
  function addPhoto(src,location,persist,recordId,savedAt,filter,sticker){if(!src)return;if(photoCount===0)$('photos').innerHTML='';const item={id:recordId??(`tmp-${Date.now()}-${Math.random().toString(16).slice(2)}`),src,location,savedAt:savedAt||Date.now(),filter:filter||null,sticker:sticker||null,selected:false};photoItems.unshift(item);photoCount=photoItems.length;$('photoCount').textContent=photoCount;updateStorageSummary();const card=document.createElement('article');card.className='photoCard';card.dataset.photoId=String(item.id);const img=document.createElement('img');img.src=src;img.alt='Participant capture';img.loading='lazy';img.onclick=()=>openPhotoViewer(item.id);const meta=document.createElement('div');meta.className='photoMeta';meta.innerHTML=`<b>${item.filter==='sticker'?'Filter':'Selfie'}</b><span>${new Date(item.savedAt).toLocaleString()}</span>${item.location?`<span>📍 ${Number(item.location.lat).toFixed(5)}, ${Number(item.location.lon).toFixed(5)}</span>`:''}`;const actions=document.createElement('div');actions.className='photoActions';const checkBox=document.createElement('input');checkBox.type='checkbox';checkBox.className='photoSelect';checkBox.onchange=()=>{item.selected=checkBox.checked;card.classList.toggle('selected',item.selected);refreshSelection()};const del=document.createElement('button');del.className='photoDelete';del.textContent='Delete';del.onclick=async e=>{e.stopPropagation();await deletePhoto(item.id);};actions.append(checkBox,del);card.append(img,meta,actions);$('photos').prepend(card)}
  async function deletePhoto(id){await dbDelete('photos',id);photoItems=photoItems.filter(x=>x.id!==id);photoCount=photoItems.length;$('photoCount').textContent=photoCount;$(`.photoCard[data-photo-id="${CSS.escape(String(id))}"]`)?.remove();if(!photoCount)$('photos').innerHTML=emptyGallery();refreshSelection();updateStorageSummary();if(viewerIndex>=photoItems.length)viewerIndex=photoItems.length-1;updateViewerNav();toast('Photo deleted');log('Photo deleted from Device A local storage.')}
  $('deleteSelectedBtn').onclick=async()=>{const ids=photoItems.filter(x=>x.selected).map(x=>x.id);for(const id of ids)await deletePhoto(id);toast(`${ids.length} photo${ids.length===1?'':'s'} deleted`)};
  $('selectAllBtn').onclick=()=>{const select=photoItems.some(x=>!x.selected);photoItems.forEach(x=>x.selected=select);document.querySelectorAll('.photoSelect').forEach(el=>el.checked=select);document.querySelectorAll('.photoCard').forEach(c=>c.classList.toggle('selected',select));refreshSelection()};
  $('clearPhotosBtn').onclick=async()=>{if(!photoCount||!confirm('Delete all received photos from Device A?'))return;await dbClear('photos');photoItems=[];photoCount=0;viewerIndex=-1;$('photoCount').textContent='0';$('photos').innerHTML=emptyGallery();updateStorageSummary();refreshSelection();closePhotoViewer();toast('All photos deleted');log('All local photos deleted from Device A.')};
  $('clearLocationBtn').onclick=async()=>{if(!confirm('Clear saved location history?'))return;await dbClear('locations');$('lat').textContent=$('lon').textContent=$('acc').textContent='—';$('locationInfo').textContent='Location history cleared';$('map').textContent='Waiting for participant location';$('openMapBtn').disabled=true;latestMapUrl='';toast('Location history cleared');log('Location history cleared from Device A.')};
  $('openMapBtn').onclick=()=>latestMapUrl&&window.open(latestMapUrl,'_blank','noopener');

  function openPhotoViewer(id){const idx=photoItems.findIndex(x=>x.id===id);if(idx<0)return;viewerIndex=idx;viewerScale=1;const modal=$('photoViewer');modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.classList.add('viewerOpen');updateViewerPhoto();}
  function updateViewerPhoto(delta=0){if(!photoItems[viewerIndex])return;const item=photoItems[viewerIndex];$('viewerImage').src=item.src;$('openOriginal').href=item.src;$('zoomLevel').textContent='100%';$('viewerImage').style.transform='scale(1)';updateViewerNav()}
  function updateViewerNav(){$('prevPhoto').disabled=viewerIndex<=0;$('nextPhoto').disabled=viewerIndex<0||viewerIndex>=photoItems.length-1}
  function closePhotoViewer(){$('photoViewer').classList.remove('show');$('photoViewer').setAttribute('aria-hidden','true');document.body.classList.remove('viewerOpen')}
  function setViewerScale(v){viewerScale=Math.max(.5,Math.min(5,v));$('viewerImage').style.transform=`scale(${viewerScale})`;$('zoomLevel').textContent=Math.round(viewerScale*100)+'%'}
  $('closeViewer').onclick=closePhotoViewer;$('photoViewer').querySelector('[data-close-viewer]').onclick=closePhotoViewer;$('zoomIn').onclick=()=>setViewerScale(viewerScale+.25);$('zoomOut').onclick=()=>setViewerScale(viewerScale-.25);$('zoomFit').onclick=()=>setViewerScale(1);$('prevPhoto').onclick=()=>{if(viewerIndex>0){viewerIndex--;updateViewerPhoto()}};$('nextPhoto').onclick=()=>{if(viewerIndex<photoItems.length-1){viewerIndex++;updateViewerPhoto()}};
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closePhotoViewer();if($('photoViewer').classList.contains('show')){if(e.key==='+')setViewerScale(viewerScale+.25);if(e.key==='-')setViewerScale(viewerScale-.25);if(e.key==='ArrowLeft'&&viewerIndex>0){viewerIndex--;updateViewerPhoto()}if(e.key==='ArrowRight'&&viewerIndex<photoItems.length-1){viewerIndex++;updateViewerPhoto()}}});
  $('exportPhotosBtn').onclick=async()=>{if(!photoItems.length){toast('No photos to export');return}const list=photoItems.map((x,i)=>({index:i+1,capturedAt:new Date(x.savedAt).toISOString(),filter:x.filter||'selfie',sticker:x.sticker||null,location:x.location||null}));const blob=new Blob([JSON.stringify({sessionId,photos:list},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`threatwatch-${sessionId}-photos.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Photo manifest exported')};
  $('clearLog').onclick=()=>{if(confirm('Clear activity history?')){$('log').textContent='';clearStoredLog();toast('Activity cleared')}};
  $('copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText($('joinUrl').textContent);toast('Participant link copied');log('Participant link copied.')}catch{toast('Copy unavailable')}};
  $('shareBtn').onclick=async()=>{const url=$('joinUrl').textContent;if(navigator.share){try{await navigator.share({title:'THREATWATCH pairing',text:'Participant session link',url});log('Participant link shared.')}catch{}}else $('copyBtn').click()};
  $('regenerateBtn').onclick=()=>{pairingToken=randomToken();sessionId=pairingToken.slice(0,20);deadline=Date.now()+SESSION_MINUTES*60000;saveSession({sessionId,pairingToken,deadline,active:true});startSession(false)};
  $('newBtn').onclick=()=>startSession(true);$('endBtn').onclick=()=>confirm('End this session and invalidate its pairing token?')&&endSession();
  $('stopLocationBtn').onclick=()=>{if(conn?.open)try{conn.send({type:'command',command:'stop-location'})}catch{}setPill('locationPill','OFF',false);$('stopLocationBtn').disabled=true;log('Stop-location requested.')};
  restoreOrStart();
})();
