(() => {
  const $=id=>document.getElementById(id);
  const p=new URLSearchParams(location.search);const session=p.get("session"),token=p.get("token");
  let peer=null,conn=null,stream=null,mediaCall=null,watchId=null,heartbeat=null,ended=false;
  const toast=msg=>{const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),2200)};
  const log=msg=>{$("log").textContent+=`[${new Date().toLocaleTimeString()}] ${msg}\n`;$('log').scrollTop=$('log').scrollHeight};
  $("clearLog").onclick=()=>$("log").textContent="";
  const badge=(text,state="neutral")=>{$("connectionBadge").textContent=text;$('connectionBadge').className=`statusBadge ${state}`};
  const setState=(id,text,on=false)=>{$(id).textContent=text;$(id).style.color=on?"#70df9f":""};
  const disableAll=()=>{$("cameraBtn").disabled=true;$('locationBtn').disabled=true;$('photoBtn').disabled=true};
  if(!session||!token){badge("INVALID","bad");$("sessionText").textContent="INVALID";$("connectionTitle").textContent="Invalid pairing link";$("message").textContent="A valid temporary session link is required.";disableAll();log("Missing session or token.");return}
  $("sessionText").textContent=session.slice(0,12)+"…";$("message").textContent="Connecting to the security console…";
  try{if(typeof Peer==="undefined")throw new Error("PeerJS library did not load");peer=new Peer(undefined,{debug:1})}catch(e){badge("ERROR","bad");$("connectionTitle").textContent="Connection unavailable";$("message").textContent="The connection library could not be loaded.";disableAll();log("Startup error: "+e.message);return}
  peer.on("open",()=>{log("Participant signaling ready.");conn=peer.connect(session,{reliable:true,metadata:{role:"participant",token}});conn.on("open",()=>{badge("CONNECTED","good");$("connectionTitle").textContent="Connected";$("message").textContent="Choose exactly what you want to share.";$("cameraBtn").disabled=false;$("locationBtn").disabled=false;conn.send({type:"hello",token,ua:navigator.userAgent});heartbeat=setInterval(()=>{if(conn?.open)conn.send({type:"heartbeat"})},5000);log("Connected to console.");toast("Session connected")});
    conn.on("data",data=>{if(!data)return;if(data.type==="pong")return;if(data.type==="command"){if(data.command==="stop-camera")stopCamera();if(data.command==="stop-location")stopLocation();if(data.command==="session-ended"){ended=true;stopCamera();stopLocation();disableAll();$("message").textContent="The console ended this session.";badge("ENDED");log("Session ended by console.");try{conn.close();peer.destroy()}catch{}}}if(data.type==="ping"&&conn?.open){try{conn.send({type:"pong",t:data.t})}catch{}}});
    conn.on("close",()=>{clearInterval(heartbeat);if(!ended){badge("DISCONNECTED");$("connectionTitle").textContent="Disconnected";$("message").textContent="The console disconnected. Reopen the pairing link to connect again.";disableAll();log("Console disconnected.")}});conn.on("error",e=>log("Data connection error: "+e.message));
  });
  peer.on("error",e=>{badge("ERROR","bad");$("connectionTitle").textContent="Connection error";$("message").textContent="Unable to connect to this session.";disableAll();log("Peer error: "+e.type+(e.message?" — "+e.message:""))});

  async function enableCamera(){if(!conn?.open)return;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera API unavailable");stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});$("localVideo").srcObject=stream;$("localEmpty").style.display="none";$("localCameraPill").textContent="ON";$("localCameraPill").className="tinyStatus on";$("cameraBtn").classList.add("active");$("cameraBtn").querySelector("em").textContent="ON";$("cameraBtn").querySelector("b").textContent="Camera active";$("photoBtn").disabled=false;mediaCall=peer.call(session,stream,{metadata:{consent:"camera-enabled"}});mediaCall.on("error",e=>log("Camera call error: "+e.message));conn.send({type:"camera",enabled:true});log("Camera enabled after browser permission.");toast("Camera sharing started")}catch(e){log("Camera permission/error: "+e.name);$("message").textContent="Camera was not enabled: "+(e.name||"permission denied");toast("Camera was not enabled")}}
  function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;try{mediaCall?.close()}catch{}mediaCall=null;$("localVideo").srcObject=null;$("localEmpty").style.display="grid";$("localCameraPill").textContent="OFF";$("localCameraPill").className="tinyStatus off";$("cameraBtn").classList.remove("active");$("cameraBtn").querySelector("em").textContent="OFF";$("cameraBtn").querySelector("b").textContent="Camera";$("photoBtn").disabled=true;try{conn?.send({type:"camera",enabled:false})}catch{}log("Camera stopped.")}
  function enableLocation(){if(!conn?.open)return;if(!navigator.geolocation){log("Geolocation unavailable.");toast("Location is unavailable");return}if(watchId!==null)return;watchId=navigator.geolocation.watchPosition(pos=>{const c=pos.coords;try{conn?.send({type:"location",lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,timestamp:Date.now()})}catch{}$("locationBtn").classList.add("active");$("locationBtn").querySelector("em").textContent="ON";$("locationBtn").querySelector("b").textContent="Location active"},err=>{log("Location permission/error: "+err.message);toast("Location was not enabled");stopLocation()},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});log("Location permission requested.")}
  function stopLocation(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;$("locationBtn").classList.remove("active");$("locationBtn").querySelector("em").textContent="OFF";$("locationBtn").querySelector("b").textContent="Location";try{conn?.send({type:"location-off"})}catch{}log("Location updates stopped.")}
  function capturePhoto(){if(!stream||!conn?.open)return;const video=$("localVideo"),track=stream.getVideoTracks()[0],s=track.getSettings();const maxW=1024,w=Math.min(s.width||1280,maxW),h=Math.round(w*((s.height||720)/(s.width||1280)));const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");ctx.drawImage(video,0,0,w,h);const data=canvas.toDataURL("image/jpeg",.68);try{conn.send({type:"photo",data})}catch(e){log("Photo send failed: "+e.message);toast("Photo could not be sent");return}$("photoState").textContent="SENT";log("Photo captured and sent with consent.");toast("Photo sent");setTimeout(()=>$("photoState").textContent="READY",1600)}
  $("cameraBtn").onclick=()=>stream?stopCamera():enableCamera();$("locationBtn").onclick=()=>watchId===null?enableLocation():stopLocation();$("photoBtn").onclick=capturePhoto;
  $("disconnectBtn").onclick=()=>{ended=true;stopCamera();stopLocation();clearInterval(heartbeat);try{conn?.close();peer?.destroy()}catch{}badge("DISCONNECTED");$("connectionTitle").textContent="Disconnected";$("message").textContent="You disconnected from the session.";disableAll();log("Participant disconnected.")};
})();
