(() => {
  const $=id=>document.getElementById(id);
  const CFG=window.THREATWATCH_CONFIG||{};
  const params=new URLSearchParams(location.search); const session=params.get('session'); const token=params.get('token');
  let peer=null,conn=null,stream=null,activeMode=''; let selectedSticker='✨'; let lastPosition=null; let watchId=null; let sending=false;
  const DB_NAME='threatwatch-device-b-v12'; let db=null;

  function openDb(){return new Promise(resolve=>{if(!('indexedDB' in window)){resolve(null);return}const req=indexedDB.open(DB_NAME,2);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('captures'))d.createObjectStore('captures',{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains('locations'))d.createObjectStore('locations',{keyPath:'id',autoIncrement:true})};req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>resolve(null)})}
  function dbAdd(store,value){if(!db)return;try{db.transaction(store,'readwrite').objectStore(store).add(value)}catch{}}
  openDb();
  const setStatus=(t,on=false)=>{$('sessionStatus').textContent=t;$('sessionStatus').className='pStatus'+(on?' on':'')};
  const msg=t=>{$('message').textContent=t};
  const enable=(yes)=>{$('selfieBtn').disabled=!yes;$('proBtn').disabled=!yes;$('filterBtn').disabled=!yes};
  if(!session||!token){setStatus('INVALID');msg('Invalid session.');enable(false);return}
  function peerOptions(){return {host:CFG.peer?.host,port:CFG.peer?.port,path:CFG.peer?.path,secure:CFG.peer?.secure,key:CFG.peer?.key,config:{iceServers:CFG.iceServers||[{urls:'stun:stun.l.google.com:19302'}],sdpSemantics:'unified-plan',iceTransportPolicy:'all'},debug:1}}
  if(typeof Peer==='undefined'){setStatus('ERROR');msg('Connection service unavailable.');enable(false);return}
  peer=new Peer(undefined,peerOptions());
  peer.on('open',()=>{conn=peer.connect(session,{reliable:true,serialization:'binary',metadata:{role:'participant',token}});conn.on('open',()=>{setStatus('CONNECTED',true);msg('Ready.');enable(true);try{conn.send({type:'hello',token,ua:navigator.userAgent})}catch{}});conn.on('data',d=>{if(d?.type==='ping'&&conn?.open)try{conn.send({type:'pong',t:d.t})}catch{}if(d?.type==='command'&&d.command==='stop-location')stopLocation();if(d?.type==='command'&&d.command==='session-ended'){stopAll();setStatus('ENDED');msg('Session ended.');enable(false)}});conn.on('close',()=>{setStatus('OFFLINE');msg('Session disconnected.');enable(false)})});
  peer.on('error',e=>{setStatus('ERROR');msg(e.type==='peer-unavailable'?'Console is not available yet.':'Unable to connect.');enable(false)});

  function showConsent(title,text,onContinue){$('permissionTitle').textContent=title;$('permissionText').textContent=text;$('permissionSheet').classList.add('show');$('permissionSheet').setAttribute('aria-hidden','false');$('permissionAllow').onclick=async()=>{closeConsent();await onContinue()};$('permissionCancel').onclick=closeConsent}
  function closeConsent(){$('permissionSheet').classList.remove('show');$('permissionSheet').setAttribute('aria-hidden','true')}

  async function openCamera(){if(!conn?.open)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:1280},height:{ideal:960}},audio:false});$('localVideo').srcObject=stream;$('stage').classList.add('show');$('selfieBtn').classList.add('active');$('proBtn').classList.add('active');$('captureBtn').textContent=activeMode==='filter'?'Apply & send':'Capture & send';msg('Camera ready. Tap Capture & send.');try{conn.send({type:'camera',enabled:true})}catch{}}catch{msg('Camera permission was not granted.')}}
  function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('localVideo').srcObject=null;$('stage').classList.remove('show');$('selfieBtn').classList.remove('active');$('proBtn').classList.remove('active');try{conn?.send({type:'camera',enabled:false})}catch{}}
  function captureCanvas(withFilter=false){if(!stream)return null;const video=$('localVideo'),track=stream.getVideoTracks()[0],s=track.getSettings();const w=Math.min(Number(s.width)||1280,1280),h=Math.round(w*((Number(s.height)||960)/(Number(s.width)||1280)));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(video,0,0,w,h);if(withFilter){ctx.fillStyle='rgba(118,91,255,.08)';ctx.fillRect(0,0,w,h);ctx.font=`${Math.max(34,Math.round(w*.08))}px system-ui`;ctx.fillStyle='rgba(255,255,255,.95)';ctx.textAlign='right';ctx.fillText(selectedSticker,w-28,Math.max(60,Math.round(h*.12)));}return c}
  function canvasToBlob(c){return new Promise(resolve=>c.toBlob(b=>resolve(b),'image/jpeg',.82))}
  async function sendPhoto(blob,meta){if(!conn?.open||!blob||sending)return;sending=true;const id=`p-${Date.now()}-${Math.random().toString(16).slice(2)}`;const buf=await blob.arrayBuffer();const chunkSize=Number(CFG.photoChunkSize||65536);const total=Math.ceil(buf.byteLength/chunkSize);try{conn.send({type:'photo-start',id,total,mime:blob.type,location:meta.location||null,filter:meta.filter||'selfie',sticker:meta.sticker||null,savedAt:Date.now(),bytes:buf.byteLength});for(let i=0;i<total;i++){const end=Math.min(buf.byteLength,(i+1)*chunkSize);while(conn?.open && Number(conn.bufferSize||0)>512*1024)await new Promise(r=>setTimeout(r,40));conn.send(buf.slice(i*chunkSize,end));await new Promise(r=>setTimeout(r,0));}dbAdd('captures',{data:await blobToDataURL(blob),location:meta.location||null,filter:meta.filter||'selfie',sticker:meta.sticker||null,savedAt:Date.now()});msg(meta.filter==='sticker'?'Filtered photo sent.':'Selfie sent.')}catch{try{conn.send({type:'cancel-photo',id})}catch{}msg('Transfer failed. Please retry.')}finally{sending=false}}
  const blobToDataURL=b=>new Promise(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>resolve('');fr.readAsDataURL(b)});

  async function takeSelfie(){if(!stream){await openCamera();return}const c=captureCanvas(false),b=await canvasToBlob(c);await sendPhoto(b,{filter:'selfie'});}
  async function takeFilter(){if(!stream){await openCamera();return}const c=captureCanvas(true),ctx=c.getContext('2d');if(lastPosition){const pad=Math.max(12,Math.round(c.width*.02));const f=Math.max(16,Math.round(c.width*.02));const boxH=f*3+pad*2;ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(pad,c.height-boxH-pad,c.width-pad*2,boxH);ctx.fillStyle='#fff';ctx.font=`600 ${f}px system-ui`;ctx.textAlign='left';ctx.fillText(`📍 ${lastPosition.lat.toFixed(5)}, ${lastPosition.lon.toFixed(5)}`,pad*1.4,c.height-boxH+pad+f);ctx.fillText(`±${Math.round(lastPosition.accuracy)} m`,pad*1.4,c.height-boxH+pad+f*2);ctx.fillText('THREATWATCH • FILTER',pad*1.4,c.height-boxH+pad+f*3)}const b=await canvasToBlob(c);await sendPhoto(b,{filter:'sticker',sticker:selectedSticker,location:lastPosition});}

  async function requestLocation(){if(lastPosition)return lastPosition;if(!navigator.geolocation)throw new Error('Unavailable');return new Promise((resolve,reject)=>{navigator.geolocation.getCurrentPosition(pos=>{const c=pos.coords;lastPosition={lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,timestamp:Date.now()};dbAdd('locations',lastPosition);try{conn?.send({type:'location',...lastPosition})}catch{}resolve(lastPosition)},reject,{enableHighAccuracy:true,maximumAge:5000,timeout:15000})})}
  function startLocation(){if(watchId!==null)return;watchId=navigator.geolocation.watchPosition(pos=>{const c=pos.coords;lastPosition={lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,timestamp:Date.now()};dbAdd('locations',lastPosition);try{conn?.send({type:'location',...lastPosition})}catch{}msg('Pro mode is active.')},()=>msg('Location permission was not granted.'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
  function stopLocation(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}try{conn?.send({type:'location-off'})}catch{}}
  function stopAll(){stopCamera();stopLocation()}

  $('selfieBtn').onclick=()=>showConsent('Selfie camera','Camera access is needed to take a selfie and send the captured photo to the paired console.',takeSelfie);
  $('proBtn').onclick=()=>showConsent('Pro mode location','Pro mode uses your browser location permission and shares location updates with the paired console while enabled.',async()=>{try{await requestLocation();startLocation();$('proBtn').classList.add('active');msg('Pro mode is active.')}catch{msg('Location permission was not granted.')}});
  $('filterBtn').onclick=()=>{$('stickerPanel').classList.add('show');activeMode='filter';showConsent('Filter capture','A filtered photo can include the selected sticker and your location, and the result is sent to the paired console.',async()=>{try{await requestLocation();await openCamera()}catch{msg('Camera and location permission are required for this filter.')}})};
  $('captureBtn').onclick=()=>activeMode==='filter'?takeFilter():takeSelfie();
  $('closeCameraBtn').onclick=stopCamera;$('closeFilterBtn').onclick=()=>{$('stickerPanel').classList.remove('show');activeMode='';msg('Choose a mode to continue.')};$('applyFilterBtn').onclick=()=>{if(!stream){msg('Open the camera first.');return}takeFilter()};
  document.querySelectorAll('.sticker').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.sticker').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selectedSticker=btn.dataset.sticker});
})();
